//go:build !diogen

// Code generated by diogen. DO NOT EDIT.

package login

import (
	"errors"
	"fmt"
	"io"
	"os"
	"runtime/debug"
	"sync"

	env "gitlab.com/gorib/env"
	pry "gitlab.com/gorib/pry"
	channels "gitlab.com/gorib/pry/channels"
	pryzerolog "gitlab.com/gorib/pry/zerolog"
	oauth2 "golang.org/x/oauth2"

	app "github.com/reindeer/magnifika_bot/config/app"
	google "github.com/reindeer/magnifika_bot/domain/bot/adapter/google"
	login "github.com/reindeer/magnifika_bot/domain/bot/cmd/login"
	authService "github.com/reindeer/magnifika_bot/domain/bot/service/auth"
)

type Application struct {
	closers               diogenClosers
	googleOauth2Config    *oauth2.Config
	googleCredentials     google.Credentials
	googleConsent         google.Consent
	authServiceAuthorizer authService.Authorizer
	loginAuth             login.Auth
	pryLogger             pry.Logger
	appCommand            app.Command
	appApp                *app.App
}

func (a *Application) GoogleOauth2Config() *oauth2.Config {
	return a.googleOauth2Config
}
func (a *Application) GoogleCredentials() google.Credentials {
	return a.googleCredentials
}
func (a *Application) GoogleConsent() google.Consent {
	return a.googleConsent
}
func (a *Application) AuthServiceAuthorizer() authService.Authorizer {
	return a.authServiceAuthorizer
}
func (a *Application) LoginAuth() login.Auth {
	return a.loginAuth
}
func (a *Application) PryLogger() pry.Logger {
	return a.pryLogger
}
func (a *Application) AppCommand() app.Command {
	return a.appCommand
}
func (a *Application) AppApp() *app.App {
	return a.appApp
}

type Replacements struct {
	// github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewAuthorization
	AuthServiceAuthorizer authService.Authorizer
	// github.com/reindeer/magnifika_bot/domain/bot/service/auth.NewAuth
	LoginAuth login.Auth
	// gitlab.com/gorib/pry.Logger
	PryLogger pry.Logger
	// github.com/reindeer/magnifika_bot/domain/bot/cmd/login.NewLogin
	AppCommand app.Command
}

func (a *Application) Shutdown() func() error {
	closers := a.closers
	return func() error {
		var errs []error
		for i := len(closers) - 1; i >= 0; i-- {
			if err := closers[i].run(); err != nil {
				errs = append(errs, err)
			}
		}
		return errors.Join(errs...)
	}
}
func InitApp() (*Application, error) {
	return InitAppWith(Replacements{})
}
func InitAppWith(replacements Replacements) (_ *Application, err error) {
	container := &Application{}
	defer func() {
		if r := recover(); r != nil && err == nil {
			err = diogenPanic(r)
		}

		// The caller is handed an error instead of the container, so nothing else can close what was built.
		if err != nil {
			if cerr := container.Shutdown()(); cerr != nil {
				err = errors.Join(err, cerr)
			}
		}
	}()

	container.authServiceAuthorizer = replacements.AuthServiceAuthorizer
	container.loginAuth = replacements.LoginAuth
	container.pryLogger = replacements.PryLogger
	container.appCommand = replacements.AppCommand

	buildGoogleOauth2Config := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewConfig", func(name string) error {
		s, err := google.NewConfig(env.NeedValue[string]("GOOGLE_CREDENTIALS"))
		if err != nil {
			return err
		}
		container.googleOauth2Config = s
		container.googleCredentials = s
		container.googleConsent = s
		return nil
	})

	buildAuthServiceAuthorizer := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewAuthorization", func(name string) error {
		if container.authServiceAuthorizer == nil {
			if err := buildGoogleOauth2Config(); err != nil {
				return err
			}
			s := google.NewAuthorization(container.googleConsent)
			container.authServiceAuthorizer = s
		}
		return nil
	})

	buildLoginAuth := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/service/auth.NewAuth", func(name string) error {
		if container.loginAuth == nil {
			if err := buildAuthServiceAuthorizer(); err != nil {
				return err
			}
			s := authService.NewAuth(container.authServiceAuthorizer)
			container.loginAuth = s
		}
		return nil
	})

	buildPryLogger := diogenBuild("gitlab.com/gorib/pry.Logger", func(name string) error {
		if container.pryLogger == nil {
			s, err := func() (pry.Logger, error) {
				level, err := pry.ParseLevel(env.Value("LOGLEVEL", "info"))
				if err != nil {
					return nil, err
				}
				sentry, err := channels.Sentry(env.Value("SENTRY_LEVEL", "error"), channels.WithSentryConnection(
					env.Value("SENTRY_DSN", ""),
					env.Value("ENVIRONMENT", "noenv"),
					channels.WithSentryService(env.Value("SERVICE", "magnifika_bot")),
				))
				if err != nil {
					return nil, err
				}
				return pry.New(level, pryzerolog.New(pryzerolog.Plain()), pry.ToSinks(sentry)), nil
			}()
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.pryLogger = s
		}
		return nil
	})

	buildAppCommand := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/cmd/login.NewLogin", func(name string) error {
		if container.appCommand == nil {
			if err := diogenNeed(buildLoginAuth, buildPryLogger); err != nil {
				return err
			}
			s := login.NewLogin(container.loginAuth, os.Stdin, container.pryLogger)
			container.appCommand = s
		}
		return nil
	})

	buildAppApp := diogenBuild("github.com/reindeer/magnifika_bot/config/app.New", func(name string) error {
		if err := diogenNeed(buildAppCommand, buildPryLogger); err != nil {
			return err
		}
		s := app.New(container.appCommand, container.pryLogger)
		container.appApp = s
		return nil
	})

	if err := buildAppApp(); err != nil {
		return nil, err
	}

	return container, nil
}

type diogenCloser struct {
	name  string
	close func() error
}
type diogenClosers []diogenCloser

func (c *diogenClosers) add(name string, close func() error) {
	*c = append(*c, diogenCloser{name, close})
}
func (c diogenCloser) run() (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("%s: %w", c.name, diogenPanic(r))
		}
	}()
	if err := c.close(); err != nil {
		return fmt.Errorf("%s: %w", c.name, err)
	}
	return nil
}

type diogenFailure struct {
	name string
	err  error
}

func (f *diogenFailure) Error() string {
	if f.name == "" {
		return f.err.Error()
	}
	return f.name + ": " + f.err.Error()
}
func (f *diogenFailure) Unwrap() error {
	return f.err
}
func diogenError(v any) error {
	if err, ok := v.(error); ok {
		return err
	}
	return fmt.Errorf("%v", v)
}
func diogenPanic(v any) error {
	return fmt.Errorf("panic: %w\n\n%s", diogenError(v), debug.Stack())
}
func diogenRun(name string, build func(name string) error) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = diogenPanic(r)
		}
		if _, named := err.(*diogenFailure); err != nil && !named {
			err = &diogenFailure{name, err}
		}
	}()
	return build(name)
}

//go:noinline
func diogenBuild(name string, build func(name string) error) func() error {
	return sync.OnceValue(func() error {
		return diogenRun(name, build)
	})
}
func diogenNeed(builds ...func() error) error {
	for _, build := range builds {
		if err := build(); err != nil {
			return err
		}
	}
	return nil
}
