version: "2"

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - wastedassign

  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
