issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'unknown JSON option "required"'
    - linters:
        - staticcheck
      text: 'only the first constant in this group has an explicit type'
