//go:build !diogen

// Code generated by diogen. DO NOT EDIT.

package migrate

import (
	dbSql "database/sql"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"runtime/debug"
	"sync"

	v3 "github.com/pressly/goose/v3"
	env "gitlab.com/gorib/env"
	pry "gitlab.com/gorib/pry"
	channels "gitlab.com/gorib/pry/channels"
	pryzerolog "gitlab.com/gorib/pry/zerolog"
	sql "gitlab.com/gorib/sql"

	app "github.com/reindeer/magnifika_bot/config/app"
	migrate "github.com/reindeer/magnifika_bot/domain/bot/cmd/migrate"
)

type Application struct {
	closers       diogenClosers
	sqlDb         sql.Db
	dbSqlDB       *dbSql.DB
	migrateFsFS   fs.FS
	gooseProvider *v3.Provider
	pryLogger     pry.Logger
	appCommand    app.Command
	appApp        *app.App
}

func (a *Application) SqlDb() sql.Db {
	return a.sqlDb
}
func (a *Application) DbSqlDB() *dbSql.DB {
	return a.dbSqlDB
}
func (a *Application) MigrateFsFS() fs.FS {
	return a.migrateFsFS
}
func (a *Application) GooseProvider() *v3.Provider {
	return a.gooseProvider
}
func (a *Application) PryLogger() pry.Logger {
	return a.pryLogger
}
func (a *Application) AppCommand() app.Command {
	return a.appCommand
}
func (a *Application) AppApp() *app.App {
	return a.appApp
}

type Replacements struct {
	// gitlab.com/gorib/sql.NewDb
	SqlDb sql.Db
	// github.com/reindeer/magnifika_bot/domain/bot/cmd/migrate.Migrations
	MigrateFsFS fs.FS
	// gitlab.com/gorib/pry.Logger
	PryLogger pry.Logger
	// github.com/reindeer/magnifika_bot/domain/bot/cmd/migrate.NewMigrator
	AppCommand app.Command
}

func (a *Application) Shutdown() func() error {
	closers := a.closers
	return func() error {
		var errs []error
		for i := len(closers) - 1; i >= 0; i-- {
			if err := closers[i].run(); err != nil {
				errs = append(errs, err)
			}
		}
		return errors.Join(errs...)
	}
}
func InitApp() (*Application, error) {
	return InitAppWith(Replacements{})
}
func InitAppWith(replacements Replacements) (_ *Application, err error) {
	container := &Application{}
	defer func() {
		if r := recover(); r != nil && err == nil {
			err = diogenPanic(r)
		}

		// The caller is handed an error instead of the container, so nothing else can close what was built.
		if err != nil {
			if cerr := container.Shutdown()(); cerr != nil {
				err = errors.Join(err, cerr)
			}
		}
	}()

	container.sqlDb = replacements.SqlDb
	container.migrateFsFS = replacements.MigrateFsFS
	container.pryLogger = replacements.PryLogger
	container.appCommand = replacements.AppCommand

	buildSqlDb := diogenBuild("gitlab.com/gorib/sql.NewDb", func(name string) error {
		if container.sqlDb == nil {
			s, err := sql.NewDb("sqlite", filepath.Join(env.Value("DB_PATH", "."), "bot.sqlite"))
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.sqlDb = s
		}
		return nil
	})

	buildDbSqlDB := diogenBuild("*database/sql.DB", func(name string) error {
		if err := buildSqlDb(); err != nil {
			return err
		}
		s, err := func(db sql.Db) (*dbSql.DB, error) { return db.DbSql() }(container.sqlDb)
		if err != nil {
			return err
		}
		container.dbSqlDB = s
		return nil
	})

	buildMigrateFsFS := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/cmd/migrate.Migrations", func(name string) error {
		if container.migrateFsFS == nil {
			s, err := migrate.Migrations()
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.migrateFsFS = s
		}
		return nil
	})

	buildGooseProvider := diogenBuild("github.com/pressly/goose/v3.NewProvider", func(name string) error {
		if err := diogenNeed(buildDbSqlDB, buildMigrateFsFS); err != nil {
			return err
		}
		s, err := v3.NewProvider(v3.DialectSQLite3, container.dbSqlDB, container.migrateFsFS, []v3.ProviderOption{v3.WithTableName("migrations")}...)
		if err != nil {
			return err
		}
		container.closers.add(name, s.Close)
		container.gooseProvider = s
		return nil
	})

	buildPryLogger := diogenBuild("gitlab.com/gorib/pry.Logger", func(name string) error {
		if container.pryLogger == nil {
			s, err := func() (pry.Logger, error) {
				level, err := pry.ParseLevel(env.Value("LOGLEVEL", "info"))
				if err != nil {
					return nil, err
				}
				sentry, err := channels.Sentry(env.Value("SENTRY_LEVEL", "error"), channels.WithSentryConnection(
					env.Value("SENTRY_DSN", ""),
					env.Value("ENVIRONMENT", "noenv"),
					channels.WithSentryService(env.Value("SERVICE", "magnifika_bot")),
				))
				if err != nil {
					return nil, err
				}
				return pry.New(level, pryzerolog.New(pryzerolog.Plain()), pry.ToSinks(sentry)), nil
			}()
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.pryLogger = s
		}
		return nil
	})

	buildAppCommand := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/cmd/migrate.NewMigrator", func(name string) error {
		if container.appCommand == nil {
			if err := diogenNeed(buildGooseProvider, buildPryLogger); err != nil {
				return err
			}
			s := migrate.NewMigrator(container.gooseProvider, container.pryLogger)
			container.appCommand = s
		}
		return nil
	})

	buildAppApp := diogenBuild("github.com/reindeer/magnifika_bot/config/app.New", func(name string) error {
		if err := diogenNeed(buildAppCommand, buildPryLogger); err != nil {
			return err
		}
		s := app.New(container.appCommand, container.pryLogger)
		container.appApp = s
		return nil
	})

	if err := buildAppApp(); err != nil {
		return nil, err
	}

	return container, nil
}

type diogenCloser struct {
	name  string
	close func() error
}
type diogenClosers []diogenCloser

func (c *diogenClosers) add(name string, close func() error) {
	*c = append(*c, diogenCloser{name, close})
}
func (c diogenCloser) run() (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("%s: %w", c.name, diogenPanic(r))
		}
	}()
	if err := c.close(); err != nil {
		return fmt.Errorf("%s: %w", c.name, err)
	}
	return nil
}

type diogenFailure struct {
	name string
	err  error
}

func (f *diogenFailure) Error() string {
	if f.name == "" {
		return f.err.Error()
	}
	return f.name + ": " + f.err.Error()
}
func (f *diogenFailure) Unwrap() error {
	return f.err
}
func diogenError(v any) error {
	if err, ok := v.(error); ok {
		return err
	}
	return fmt.Errorf("%v", v)
}
func diogenPanic(v any) error {
	return fmt.Errorf("panic: %w\n\n%s", diogenError(v), debug.Stack())
}
func diogenRun(name string, build func(name string) error) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = diogenPanic(r)
		}
		if _, named := err.(*diogenFailure); err != nil && !named {
			err = &diogenFailure{name, err}
		}
	}()
	return build(name)
}

//go:noinline
func diogenBuild(name string, build func(name string) error) func() error {
	return sync.OnceValue(func() error {
		return diogenRun(name, build)
	})
}
func diogenNeed(builds ...func() error) error {
	for _, build := range builds {
		if err := build(); err != nil {
			return err
		}
	}
	return nil
}
