//go:build !store

// Code generated by sql.store; DO NOT EDIT.
package sqlite

import (
	model "github.com/reindeer/magnifika_bot/domain/bot/model"
)

var storedCustomerMappings = map[string]string{
	"id":    "customer_id",
	"phone": "phone",
}

func newStoredCustomer(m *model.Customer) *storedCustomer {
	return &storedCustomer{
		Id:    m.Id,
		Phone: m.Phone,
	}
}

func (m *storedCustomer) Unwrap() *model.Customer {
	return &model.Customer{
		Id:    m.Id,
		Phone: m.Phone,
	}
}

func (m *storedCustomer) Mappings() map[string]string {
	return storedCustomerMappings
}

func (m *storedCustomer) DefaultSort() []string {
	return []string{
		"customer_id",
	}
}

func (m *storedCustomer) Updates() map[string]any {
	return map[string]any{
		"customer_id": m.Id,
		"phone":       m.Phone,
	}
}

func (m *storedCustomer) Inserts() ([]string, []any) {
	return []string{
		"customer_id",
		"phone",
	}, []any{
		m.Id,
		m.Phone,
	}
}

func (m *storedCustomer) Returns() []string {
	return []string{
		"customer_id",
		"phone",
	}
}

func (m *storedCustomer) Scan() []any {
	return []any{
		&m.Id,
		&m.Phone,
	}
}
