//go:build !diogen

// Code generated by diogen. DO NOT EDIT.

package serve

import (
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"runtime/debug"
	"sync"

	bot "github.com/go-telegram/bot"
	env "gitlab.com/gorib/env"
	pry "gitlab.com/gorib/pry"
	channels "gitlab.com/gorib/pry/channels"
	pryzerolog "gitlab.com/gorib/pry/zerolog"
	sql "gitlab.com/gorib/sql"
	oauth2 "golang.org/x/oauth2"

	app "github.com/reindeer/magnifika_bot/config/app"
	google "github.com/reindeer/magnifika_bot/domain/bot/adapter/google"
	sqlite "github.com/reindeer/magnifika_bot/domain/bot/adapter/sqlite"
	telegram "github.com/reindeer/magnifika_bot/domain/bot/adapter/telegram"
	serve "github.com/reindeer/magnifika_bot/domain/bot/cmd/serve"
	botService "github.com/reindeer/magnifika_bot/domain/bot/service/bot"
)

type Application struct {
	closers                diogenClosers
	botBot                 *bot.Bot
	telegramSender         telegram.Sender
	serveUpdates           serve.Updates
	sqlDb                  sql.Db
	botServiceCustomers    botService.Customers
	googleOauth2Config     *oauth2.Config
	googleCredentials      google.Credentials
	googleConsent          google.Consent
	botServicePhones       botService.Phones
	botServiceApplications botService.Applications
	botServiceMessenger    botService.Messenger
	pryLogger              pry.Logger
	serveBot               serve.Bot
	appCommand             app.Command
	appApp                 *app.App
}

func (a *Application) BotBot() *bot.Bot {
	return a.botBot
}
func (a *Application) TelegramSender() telegram.Sender {
	return a.telegramSender
}
func (a *Application) ServeUpdates() serve.Updates {
	return a.serveUpdates
}
func (a *Application) SqlDb() sql.Db {
	return a.sqlDb
}
func (a *Application) BotServiceCustomers() botService.Customers {
	return a.botServiceCustomers
}
func (a *Application) GoogleOauth2Config() *oauth2.Config {
	return a.googleOauth2Config
}
func (a *Application) GoogleCredentials() google.Credentials {
	return a.googleCredentials
}
func (a *Application) GoogleConsent() google.Consent {
	return a.googleConsent
}
func (a *Application) BotServicePhones() botService.Phones {
	return a.botServicePhones
}
func (a *Application) BotServiceApplications() botService.Applications {
	return a.botServiceApplications
}
func (a *Application) BotServiceMessenger() botService.Messenger {
	return a.botServiceMessenger
}
func (a *Application) PryLogger() pry.Logger {
	return a.pryLogger
}
func (a *Application) ServeBot() serve.Bot {
	return a.serveBot
}
func (a *Application) AppCommand() app.Command {
	return a.appCommand
}
func (a *Application) AppApp() *app.App {
	return a.appApp
}

type Replacements struct {
	// gitlab.com/gorib/sql.NewDb
	SqlDb sql.Db
	// github.com/reindeer/magnifika_bot/domain/bot/adapter/sqlite.NewCustomers
	BotServiceCustomers botService.Customers
	// github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewSheets
	GoogleSpreadsheets interface {
		botService.Phones
		botService.Applications
	}
	// github.com/reindeer/magnifika_bot/domain/bot/adapter/telegram.NewMessenger
	BotServiceMessenger botService.Messenger
	// gitlab.com/gorib/pry.Logger
	PryLogger pry.Logger
	// github.com/reindeer/magnifika_bot/domain/bot/service/bot.NewBot
	ServeBot serve.Bot
	// github.com/reindeer/magnifika_bot/domain/bot/cmd/serve.NewServer
	AppCommand app.Command
}

func (a *Application) Shutdown() func() error {
	closers := a.closers
	return func() error {
		var errs []error
		for i := len(closers) - 1; i >= 0; i-- {
			if err := closers[i].run(); err != nil {
				errs = append(errs, err)
			}
		}
		return errors.Join(errs...)
	}
}
func InitApp() (*Application, error) {
	return InitAppWith(Replacements{})
}
func InitAppWith(replacements Replacements) (_ *Application, err error) {
	container := &Application{}
	defer func() {
		if r := recover(); r != nil && err == nil {
			err = diogenPanic(r)
		}

		// The caller is handed an error instead of the container, so nothing else can close what was built.
		if err != nil {
			if cerr := container.Shutdown()(); cerr != nil {
				err = errors.Join(err, cerr)
			}
		}
	}()

	container.sqlDb = replacements.SqlDb
	container.botServiceCustomers = replacements.BotServiceCustomers
	container.botServicePhones = replacements.GoogleSpreadsheets
	container.botServiceApplications = replacements.GoogleSpreadsheets
	container.botServiceMessenger = replacements.BotServiceMessenger
	container.pryLogger = replacements.PryLogger
	container.serveBot = replacements.ServeBot
	container.appCommand = replacements.AppCommand

	buildBotBot := diogenBuild("github.com/go-telegram/bot.New", func(name string) error {
		s, err := bot.New(env.NeedValue[string]("TELEGRAM_TOKEN"), []bot.Option{bot.WithSkipGetMe(), bot.WithNotAsyncHandlers()}...)
		if err != nil {
			return err
		}
		container.botBot = s
		container.telegramSender = s
		container.serveUpdates = s
		return nil
	})

	buildSqlDb := diogenBuild("gitlab.com/gorib/sql.NewDb", func(name string) error {
		if container.sqlDb == nil {
			s, err := sql.NewDb("sqlite", filepath.Join(env.Value("DB_PATH", "."), "bot.sqlite"))
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.sqlDb = s
		}
		return nil
	})

	buildBotServiceCustomers := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/sqlite.NewCustomers", func(name string) error {
		if container.botServiceCustomers == nil {
			if err := buildSqlDb(); err != nil {
				return err
			}
			s, err := sqlite.NewCustomers(container.sqlDb)
			if err != nil {
				return err
			}
			container.botServiceCustomers = s
		}
		return nil
	})

	buildGoogleOauth2Config := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewConfig", func(name string) error {
		s, err := google.NewConfig(env.NeedValue[string]("GOOGLE_CREDENTIALS"))
		if err != nil {
			return err
		}
		container.googleOauth2Config = s
		container.googleCredentials = s
		container.googleConsent = s
		return nil
	})

	buildGoogleSpreadsheets := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/google.NewSheets", func(name string) error {
		if container.botServicePhones == nil {
			if err := buildGoogleOauth2Config(); err != nil {
				return err
			}
			s, err := google.NewSheets(container.googleCredentials, env.NeedJson[*oauth2.Token]("GOOGLE_TOKEN"), env.NeedValue[string]("GOOGLE_APPLICATION_SHEET"), env.NeedValue[string]("GOOGLE_VALIDATION_SHEET"), env.NeedArray[string]("GATES"))
			if err != nil {
				return err
			}
			container.botServicePhones = s
			container.botServiceApplications = s
		}
		return nil
	})

	buildBotServiceMessenger := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/adapter/telegram.NewMessenger", func(name string) error {
		if container.botServiceMessenger == nil {
			if err := buildBotBot(); err != nil {
				return err
			}
			s := telegram.NewMessenger(container.telegramSender)
			container.botServiceMessenger = s
		}
		return nil
	})

	buildPryLogger := diogenBuild("gitlab.com/gorib/pry.Logger", func(name string) error {
		if container.pryLogger == nil {
			s, err := func() (pry.Logger, error) {
				level, err := pry.ParseLevel(env.Value("LOGLEVEL", "info"))
				if err != nil {
					return nil, err
				}
				sentry, err := channels.Sentry(env.Value("SENTRY_LEVEL", "error"), channels.WithSentryConnection(
					env.Value("SENTRY_DSN", ""),
					env.Value("ENVIRONMENT", "noenv"),
					channels.WithSentryService(env.Value("SERVICE", "magnifika_bot")),
				))
				if err != nil {
					return nil, err
				}
				return pry.New(level, pryzerolog.New(pryzerolog.Plain()), pry.ToSinks(sentry)), nil
			}()
			if err != nil {
				return err
			}
			if v, ok := any(s).(io.Closer); ok {
				container.closers.add(name, v.Close)
			}
			container.pryLogger = s
		}
		return nil
	})

	buildServeBot := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/service/bot.NewBot", func(name string) error {
		if container.serveBot == nil {
			if err := diogenNeed(buildBotServiceCustomers, buildGoogleSpreadsheets, buildBotServiceMessenger, buildPryLogger); err != nil {
				return err
			}
			s, err := botService.NewBot(env.NeedValue[string]("PHONE_GUARD"), env.NeedValue[string]("PHONE_DISPATCHER"), env.NeedValue[string]("PHONE_EMERGENCY"), container.botServiceCustomers, container.botServicePhones, container.botServiceApplications, container.botServiceMessenger, container.pryLogger)
			if err != nil {
				return err
			}
			container.serveBot = s
		}
		return nil
	})

	buildAppCommand := diogenBuild("github.com/reindeer/magnifika_bot/domain/bot/cmd/serve.NewServer", func(name string) error {
		if container.appCommand == nil {
			if err := diogenNeed(buildBotBot, buildServeBot, buildPryLogger); err != nil {
				return err
			}
			s := serve.NewServer(container.serveUpdates, container.serveBot, container.pryLogger)
			container.appCommand = s
		}
		return nil
	})

	buildAppApp := diogenBuild("github.com/reindeer/magnifika_bot/config/app.New", func(name string) error {
		if err := diogenNeed(buildAppCommand, buildPryLogger); err != nil {
			return err
		}
		s := app.New(container.appCommand, container.pryLogger)
		container.appApp = s
		return nil
	})

	if err := buildAppApp(); err != nil {
		return nil, err
	}

	return container, nil
}

type diogenCloser struct {
	name  string
	close func() error
}
type diogenClosers []diogenCloser

func (c *diogenClosers) add(name string, close func() error) {
	*c = append(*c, diogenCloser{name, close})
}
func (c diogenCloser) run() (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("%s: %w", c.name, diogenPanic(r))
		}
	}()
	if err := c.close(); err != nil {
		return fmt.Errorf("%s: %w", c.name, err)
	}
	return nil
}

type diogenFailure struct {
	name string
	err  error
}

func (f *diogenFailure) Error() string {
	if f.name == "" {
		return f.err.Error()
	}
	return f.name + ": " + f.err.Error()
}
func (f *diogenFailure) Unwrap() error {
	return f.err
}
func diogenError(v any) error {
	if err, ok := v.(error); ok {
		return err
	}
	return fmt.Errorf("%v", v)
}
func diogenPanic(v any) error {
	return fmt.Errorf("panic: %w\n\n%s", diogenError(v), debug.Stack())
}
func diogenRun(name string, build func(name string) error) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = diogenPanic(r)
		}
		if _, named := err.(*diogenFailure); err != nil && !named {
			err = &diogenFailure{name, err}
		}
	}()
	return build(name)
}

//go:noinline
func diogenBuild(name string, build func(name string) error) func() error {
	return sync.OnceValue(func() error {
		return diogenRun(name, build)
	})
}
func diogenNeed(builds ...func() error) error {
	for _, build := range builds {
		if err := build(); err != nil {
			return err
		}
	}
	return nil
}
